In [2]:
import os
os.getcwd()

'E:\\20190923 Newcastle-M.Res\\OneDrive - Newcastle University\\21_22_autumn\\211018\\code'

In [2]:
import pandas as pd
import json
import urllib as u

In [3]:
def Train(date,time):
    values = {}
    values['app_id']=origValue['app_id']
    values['app_key']=origValue['app_key']
    values['train_status']=origValue['train_status']
    qprams = u.parse.urlencode(values)
    uprams = date+'/'+time+'/'+'timetable.json?'
    url = u.request.urlopen(domain+uprams+qprams).read()
    result = json.loads(url)
    return result

In [ ]:
def Allday(date):
    values = {}
    values['app_id']=origValue['app_id']
    values['app_key']=origValue['app_key']
    values['train_status']=origValue['train_status']
    qprams = u.parse.urlencode(values)
    uprams = date+'/'+time+'/'+'timetable.json?'

In [ ]:
time =

 ### Main

In [4]:
origValue = {'app_id':'708dc056','app_key':'4ba32af8f9ff321c887c430198f81423','train_status':'freight'}
domain = 'https://transportapi.com/v3/uk/train/station/tiploc:jarrgbf/'
date = 'date'
time = 'time'

In [5]:
result = Train('2021-11-11', '17:00')

In [6]:
type(result)

dict

In [22]:
r= result['departures']['all']

In [23]:
r

[{'mode': 'train',
  'service': '56461880',
  'train_uid': 'H13222',
  'platform': None,
  'operator': 'ZZ',
  'operator_name': 'GB Railfreight',
  'aimed_departure_time': '17:43',
  'aimed_arrival_time': None,
  'aimed_pass_time': None,
  'origin_name': 'Tyne Dock Import Terminal',
  'destination_name': 'Drax Gb Railfreight',
  'source': 'ATOC',
  'category': None,
  'service_timetable': {'id': 'https://transportapi.com/v3/uk/train/service/train_uid:H13222/2021-11-11/timetable.json?app_id=708dc056&app_key=4ba32af8f9ff321c887c430198f81423'}}]

In [24]:
(pd.DataFrame(r)).columns

Index(['mode', 'service', 'train_uid', 'platform', 'operator', 'operator_name',
       'aimed_departure_time', 'aimed_arrival_time', 'aimed_pass_time',
       'origin_name', 'destination_name', 'source', 'category',
       'service_timetable'],
      dtype='object')

In [27]:
list((pd.DataFrame(r)).columns)

['mode',
 'service',
 'train_uid',
 'platform',
 'operator',
 'operator_name',
 'aimed_departure_time',
 'aimed_arrival_time',
 'aimed_pass_time',
 'origin_name',
 'destination_name',
 'source',
 'category',
 'service_timetable']

In [26]:
(pd.DataFrame(r)).head()

,mode,service,train_uid,platform,operator,operator_name,aimed_departure_time,aimed_arrival_time,aimed_pass_time,origin_name,destination_name,source,category,service_timetable
0,train,56461880,H13222,None,ZZ,GB Railfreight,17:43,None,None,Tyne Dock Import Terminal,Drax Gb Railfreight,ATOC,None,{'id': 'https://transportapi.com/v3/uk/train/s...

In [46]:
 print(Train('2021-11-10', '00:00')['departures']['all'])

[]

In [47]:
 print(Train('2021-11-10', '02:00')['departures']['all'])

[{'mode': 'train', 'service': '56461880', 'train_uid': 'H13176', 'platform': None, 'operator': 'ZZ', 'operator_name': 'GB Railfreight', 'aimed_departure_time': '02:30', 'aimed_arrival_time': None, 'aimed_pass_time': None, 'origin_name': 'Tyne Dock Import Terminal', 'destination_name': 'Drax Gb Railfreight', 'source': 'ATOC', 'category': None, 'service_timetable': {'id': 'https://transportapi.com/v3/uk/train/service/train_uid:H13176/2021-11-10/timetable.json?app_id=708dc056&app_key=4ba32af8f9ff321c887c430198f81423'}}]

In [48]:
 print(Train('2021-11-10', '04:00')['departures']['all'])

[{'mode': 'train', 'service': '56461880', 'train_uid': 'H13455', 'platform': None, 'operator': 'ZZ', 'operator_name': 'GB Railfreight', 'aimed_departure_time': '05:00', 'aimed_arrival_time': None, 'aimed_pass_time': None, 'origin_name': 'Tyne Dock Import Terminal', 'destination_name': 'Lynemouth Power Stn (Gbrf)', 'source': 'ATOC', 'category': None, 'service_timetable': {'id': 'https://transportapi.com/v3/uk/train/service/train_uid:H13455/2021-11-10/timetable.json?app_id=708dc056&app_key=4ba32af8f9ff321c887c430198f81423'}}]

In [49]:
 print(Train('2021-11-10', '06:00')['departures']['all'])

[{'mode': 'train', 'service': '56461880', 'train_uid': 'H13158', 'platform': None, 'operator': 'ZZ', 'operator_name': 'GB Railfreight', 'aimed_departure_time': '06:24', 'aimed_arrival_time': None, 'aimed_pass_time': None, 'origin_name': 'Tyne Dock Import Terminal', 'destination_name': 'Drax Gb Railfreight', 'source': 'ATOC', 'category': None, 'service_timetable': {'id': 'https://transportapi.com/v3/uk/train/service/train_uid:H13158/2021-11-10/timetable.json?app_id=708dc056&app_key=4ba32af8f9ff321c887c430198f81423'}}]

In [50]:
 print(Train('2021-11-10', '08:00')['departures']['all'])

[{'mode': 'train', 'service': '56461880', 'train_uid': 'H13459', 'platform': None, 'operator': 'ZZ', 'operator_name': 'GB Railfreight', 'aimed_departure_time': '09:29', 'aimed_arrival_time': None, 'aimed_pass_time': None, 'origin_name': 'Tyne Dock Import Terminal', 'destination_name': 'Lynemouth Power Stn (Gbrf)', 'source': 'ATOC', 'category': None, 'service_timetable': {'id': 'https://transportapi.com/v3/uk/train/service/train_uid:H13459/2021-11-10/timetable.json?app_id=708dc056&app_key=4ba32af8f9ff321c887c430198f81423'}}]

In [51]:
 print(Train('2021-11-10', '10:00')['departures']['all'])

[]

In [52]:
 print(Train('2021-11-10', '12:00')['departures']['all'])

[{'mode': 'train', 'service': '56461880', 'train_uid': 'H13203', 'platform': None, 'operator': 'ZZ', 'operator_name': 'GB Railfreight', 'aimed_departure_time': '12:19', 'aimed_arrival_time': None, 'aimed_pass_time': None, 'origin_name': 'Tyne Dock Import Terminal', 'destination_name': 'Drax Gb Railfreight', 'source': 'ATOC', 'category': None, 'service_timetable': {'id': 'https://transportapi.com/v3/uk/train/service/train_uid:H13203/2021-11-10/timetable.json?app_id=708dc056&app_key=4ba32af8f9ff321c887c430198f81423'}}]

In [53]:
 print(Train('2021-11-10', '14:00')['departures']['all'])

[{'mode': 'train', 'service': '56461880', 'train_uid': 'H13441', 'platform': None, 'operator': 'ZZ', 'operator_name': 'GB Railfreight', 'aimed_departure_time': '14:30', 'aimed_arrival_time': None, 'aimed_pass_time': None, 'origin_name': 'Tyne Dock Import Terminal', 'destination_name': 'Lynemouth Power Stn (Gbrf)', 'source': 'ATOC', 'category': None, 'service_timetable': {'id': 'https://transportapi.com/v3/uk/train/service/train_uid:H13441/2021-11-10/timetable.json?app_id=708dc056&app_key=4ba32af8f9ff321c887c430198f81423'}}]

In [54]:
 print(Train('2021-11-10', '16:00')['departures']['all'])

[{'mode': 'train', 'service': '56461880', 'train_uid': 'H13182', 'platform': None, 'operator': 'ZZ', 'operator_name': 'GB Railfreight', 'aimed_departure_time': '16:49', 'aimed_arrival_time': None, 'aimed_pass_time': None, 'origin_name': 'Tyne Dock Import Terminal', 'destination_name': 'Drax Gb Railfreight', 'source': 'ATOC', 'category': None, 'service_timetable': {'id': 'https://transportapi.com/v3/uk/train/service/train_uid:H13182/2021-11-10/timetable.json?app_id=708dc056&app_key=4ba32af8f9ff321c887c430198f81423'}}, {'mode': 'train', 'service': '56461880', 'train_uid': 'H13222', 'platform': None, 'operator': 'ZZ', 'operator_name': 'GB Railfreight', 'aimed_departure_time': '17:43', 'aimed_arrival_time': None, 'aimed_pass_time': None, 'origin_name': 'Tyne Dock Import Terminal', 'destination_name': 'Drax Gb Railfreight', 'source': 'ATOC', 'category': None, 'service_timetable': {'id': 'https://transportapi.com/v3/uk/train/service/train_uid:H13222/2021-11-10/timetable.json?app_id=708dc056&app_key=4ba32af8f9ff321c887c430198f81423'}}]

In [55]:
 print(Train('2021-11-10', '18:00')['departures']['all'])

[{'mode': 'train', 'service': '56461880', 'train_uid': 'H13462', 'platform': None, 'operator': 'ZZ', 'operator_name': 'GB Railfreight', 'aimed_departure_time': '19:55', 'aimed_arrival_time': None, 'aimed_pass_time': None, 'origin_name': 'Tyne Dock Import Terminal', 'destination_name': 'Lynemouth Power Stn (Gbrf)', 'source': 'ATOC', 'category': None, 'service_timetable': {'id': 'https://transportapi.com/v3/uk/train/service/train_uid:H13462/2021-11-10/timetable.json?app_id=708dc056&app_key=4ba32af8f9ff321c887c430198f81423'}}]

In [56]:
 print(Train('2021-11-10', '20:00')['departures']['all'])

[]

In [57]:
 print(Train('2021-11-10', '22:00')['departures']['all'])

[]

In [60]:
urllive = 'https://transportapi.com/v3/uk/train/station/tiploc:jarrgbf/live.json?app_id=708dc056&app_key=4ba32af8f9ff321c887c430198f81423&darwin=false&train_status=freight'

In [66]:
livedata = pd.DataFrame(json.loads(u.request.urlopen(urllive).read()))

In [70]:
list(livedata.columns)

['date',
 'time_of_day',
 'request_time',
 'station_name',
 'station_code',
 'departures']

In [71]:
livedata.head()

,date,time_of_day,request_time,station_name,station_code,departures
all,2021-11-11,12:24,2021-11-11T12:24:25+00:00,Tyne Dock Import Terminal,tiploc:jarrgbf,[]

In [82]:
import datetime

print('Timestamp: {:%H:%M}'.format(datetime.datetime.now()))

Timestamp: 14:52

In [84]:
print('Timestamp: {:%Y-%m-%d %H:%M:%S}'.format(datetime.datetime.now()))
print('Timestamp: {:%Y-%b-%d %H:%M:%S}'.format(datetime.datetime.now()))

Timestamp: 2021-11-11 14:53:27
Timestamp: 2021-Nov-11 14:53:27

In [85]:
print('Date now: %s' % datetime.datetime.now())
print('Date today: %s' % datetime.date.today())

Date now: 2021-11-11 14:53:57.438946
Date today: 2021-11-11

In [87]:
print('Date now: %s' % datetime.date.now())

AttributeError: type object 'datetime.date' has no attribute 'now'